---
- name: Mac Setup
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks
  hosts: 127.0.0.1
  connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/become.html#id1
  # become: yes
  vars:
    brew_taps:
      - homebrew/core
      - homebrew/cask
    brew_packages:
      # treeコマンド
      - tree
      # wgetコマンド
      - wget
      # Git
      - git
      # Git LFS
      - git-lfs
      # Docker Compose
      - docker-compose
      # AWS CLI
      - awscli
      # Hugo
      - hugo
    brew_cask_apps:
      # Chrome
      - google-chrome
      # Google 日本語入力
      - google-japanese-ime
      # Googleのバックアップと動機
      - google-backup-and-sync
      # iTerm2 ターミナル
      - iterm2
      # LICEcap 
      - licecap
      # Docker
      - docker
      # Vagrant
      - vagrant
      # VirtualBox
      - virtualbox
      # Visual Studio Code
      - visual-studio-code
      # Source Tree
      - sourcetree
  
  # pre_tasks:
    ## https://brew.sh/
    # - name: Install Homebrew
    #   command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

  tasks:
    # https://docs.ansible.com/ansible/2.9/modules/homebrew_tap_module.html
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"

    # https://docs.ansible.com/ansible/2.9/modules/homebrew_cask_module.html
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"

    - name: Update Homebrew Cask Packages
      homebrew_cask:
        update_homebrew: yes
        upgrade_all: yes

    # https://docs.ansible.com/ansible/2.9/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
